apiVersion: v1
kind: Service
metadata:
  name: mlflow-postgresql
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  ports:
    - name: mlflow-postgresql
      nodePort: 0
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    name: mlflow-postgresql
  sessionAffinity: None
  type: ClusterIP