apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/component: minio
    app.kubernetes.io/instance: minio
    app.kubernetes.io/name: minio
    app.kubernetes.io/part-of: minio
    component: minio
  name: create-minio-buckets
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  selector: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: minio
        app.kubernetes.io/instance: minio
        app.kubernetes.io/name: minio
        app.kubernetes.io/part-of: minio
        component: minio
    spec:
      containers:
        - command:
            - python
            - /scripts/create_bucket.py
          envFrom:
          - secretRef:
              name: minio-root-user
          env:
            - name: MODEL_BUCKET
              value: {{ .Values.buckets.models }}
            - name: PIPELINE_ARTIFACTS_BUCKET
              value: {{ .Values.buckets.pipelineArtifacts }}
          imagePullPolicy: IfNotPresent
          name: create-buckets
          restartPolicy: Never
          volumeMounts:
            - name: scripts
              mountPath: /scripts
          volumes:
            - name: scripts
              configMap:
                name: create-bucket
                defaultMode: 0755
