apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: minio
    app.kubernetes.io/component: minio
    app.kubernetes.io/instance: minio
    app.kubernetes.io/name: minio
    app.kubernetes.io/part-of: minio
    component: minio
  name: minio
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi