apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: {{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  ports:
    - name: postgresql
      nodePort: 0
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    name: postgresql
  sessionAffinity: None
  type: ClusterIP