apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-pipeline-server
spec:
  destination:
    name: in-cluster
    namespace: pipeline-server
  source:
    path: helm/20-pipeline-server/
    repoURL: https://github.com/redhat-ai-americas/demo-templates-argo.git
    targetRevision: HEAD
    helm:
      parameters:
        - name: minio.buckets.rootUser
          value: minio
        - name: minio.buckets.rootPassword
          value: minio!23
  sources: []
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 3
        maxDuration: 30m
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops