apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trusty-configuration
spec:
  destination:
    name: in-cluster
    namespace: redhat-ods-applications
  source:
    path: argo/trusty-configuration/
    repoURL: https://github.com/redhat-ai-americas/demo-templates-argo.git
    targetRevision: trusty
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 3
        maxDuration: 30m
