kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-url-getter-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
rules:
  - verbs:
      - create
      - delete
      - get
    apiGroups:
      - ''
    resources:
      - secrets
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-url-getter-{{ .Release.Namespace }}
  namespace: openshift-console
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
rules:
  - verbs:
      - get
    apiGroups:
      - route.openshift.io
    resources:
      - routes