apiVersion: datasciencepipelinesapplications.opendatahub.io/v1
kind: DataSciencePipelinesApplication
metadata:
  finalizers:
    - datasciencepipelinesapplications.opendatahub.io/finalizer
  name: dspa
  namespace: hoi
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  apiServer:
    caBundleFileMountPath: ''
    caBundleFileName: ''
    deploy: true
    artifactSignedURLExpirySeconds: 60
    enableSamplePipeline: false
    managedPipelines:
      instructLab:
        state: Removed
    enableOauth: true
    cacheEnabled: true
    pipelineStore: database
  database:
    disableHealthCheck: false
    mariaDB:
      deploy: true
      pipelineDBName: mlpipeline
      pvcSize: 10Gi
      username: mlpipeline
  dspVersion: v2
  objectStorage:
    disableHealthCheck: false
    enableExternalRoute: false
    externalStorage:
      basePath: ''
      bucket: pipeline-artifacts
      host: minio-s3{{ (lookup "v1" "Secret" .Release.Namespace "cluster-url").data.BASE_URL | b64dec }}
      port: ''
      region: us-east-1
      s3CredentialsSecret:
        accessKey: AWS_ACCESS_KEY_ID
        secretKey: AWS_SECRET_ACCESS_KEY
        secretName: pipeline-artifacts
      scheme: https
  persistenceAgent:
    deploy: true
    numWorkers: 2
  podToPodTLS: true
  scheduledWorkflow:
    cronScheduleTimezone: UTC
    deploy: true
