minio:
  enabled: true

  buckets:
    models: models
    pipelineArtifacts: pipeline-artifacts
    rootUser: 'minio'
    rootPassword: 'minio!23'

database:
  user: 'mlflowuser'
  password: 'mlflowpassword'
  database: 'mlflow'
