apiVersion: v2
name: minio
description: GitOps for deploying a MinIO instance for S3-like storage.

type: application

version: 0.1.0

appVersion: "1.0.0"

dependencies:
  - name: cluster-url-getter
    version: 0.1.0
    repository: "file://../../../helm/cluster-url-getter"
    condition: cluster-url-getter.enabled