apiVersion: v1
kind: Secret
metadata:
  annotations:
    opendatahub.io/connection-type: s3
    openshift.io/display-name: Model Storage
    argocd.argoproj.io/sync-wave: "20"
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/managed: "true"
  name: mlflow-models
  namespace: {{ .Release.Namespace }}
data:
  AWS_ACCESS_KEY_ID: {{ .Values.minio.buckets.rootUser | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.minio.buckets.rootPassword | b64enc }}
  AWS_DEFAULT_REGION: {{ print "us-east-1" | b64enc }}
  AWS_S3_BUCKET: {{ .Values.minio.buckets.models | b64enc }}
  MLFLOW_S3_ENDPOINT_URL: {{ print "http://minio." .Release.Namespace ".svc.cluster.local:9000" | b64enc }}
type: Opaque