kind: Service
apiVersion: v1
metadata:
  name: trusty-{{ .Release.Name }}
  namespace: trusty
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "21"
  labels:
    app: trusty-{{ .Release.Name }}
    app.kubernetes.io/component: trusty
    app.kubernetes.io/instance: trusty
spec:
  ports:
    - name: db
      protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
  selector:
    deployment: trusty-{{ .Release.Name }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: trusty-{{ .Release.Name }}
  namespace: trusty
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "21"
  labels:
    app: trusty-{{ .Release.Name }}
    app.kubernetes.io/component: trusty
    app.kubernetes.io/instance: trusty
spec:
  replicas: 1
  selector:
    matchLabels:
      name: trusty-{{ .Release.Name }}
  template:
    metadata:
      labels:
        name: trusty-{{ .Release.Name }}
    spec:
      containers:
        - name: trusty-db
          env:
            - name: MARIADB_RANDOM_ROOT_PASSWORD
              value: 'true'
            - name: MYSQL_DATABASE
              value: trusty
            - name: MYSQL_PASSWORD
              value: trustyai
            - name: MYSQL_USER
              value: trusty
          ports:
            - containerPort: 3306
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: trusty-volume-1
              mountPath: /var/lib/mysql
          image: 'quay.io/mariadb-foundation/mariadb-devel:11.8-ubi'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: trusty-volume-1
          emptyDir: {}
  strategy:
    type: RollingUpdate
