kind: Secret
apiVersion: v1
metadata:
  name: trusty
  namespace: trusty
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "20"
type: Opaque
data:
  MYSQL_USER: {{ .Values.database.user | b64enc }}
  MYSQL_PASSWORD: {{ .Values.database.password | b64enc }}
  MYSQL_ROOT_PASSWORD: {{ .Values.database.rootPassword | b64enc }}
  MYSQL_DATABASE: {{ "trusty" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "20"
type: Opaque
data:
  databaseKind: {{ "mariadb" | b64enc }}
  databaseUsername: {{ .Values.database.user | b64enc }}
  databasePassword: {{ .Values.database.password | b64enc }}
  databaseService: {{ printf "trusty-%s.trusty.svc.cluster.local" .Release.Name | b64enc }}
  databasePort: {{ "3306" | b64enc }}
  databaseGeneration: {{ "create" | b64enc }}
  databaseName: {{ "trusty" | b64enc }}