apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: trustyai-service-pipeline-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "21"
spec:
  podSelector:
    matchLabels:
      app: trustyai-service
      app.kubernetes.io/instance: trustyai-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              pipelines.kubeflow.org/v2_component: "true"
      ports:
        - port: 4443
          protocol: TCP